# Generated by Django 3.2.3 on 2021-05-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='https://image.shutterstock.com/image-vector/man-avatar-profile-picture-vector-260nw-229692004.jpg', null=True, upload_to='userImages'),
        ),
    ]
